// Code generated by "stringer -type=Actions -trimprefix Action"; DO NOT EDIT.

package chkb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionNil - -1]
	_ = x[ActionMap-0]
	_ = x[ActionDown-1]
	_ = x[ActionUp-2]
	_ = x[ActionTap-3]
	_ = x[ActionDoubleTap-4]
	_ = x[ActionHold-5]
	_ = x[ActionPushLayer-6]
	_ = x[ActionPopLayer-7]
}

const _Actions_name = "NilMapDownUpTapDoubleTapHoldPushLayerPopLayer"

var _Actions_index = [...]uint8{0, 3, 6, 10, 12, 15, 24, 28, 37, 45}

func (i Actions) String() string {
	i -= -1
	if i < 0 || i >= Actions(len(_Actions_index)-1) {
		return "Actions(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Actions_name[_Actions_index[i]:_Actions_index[i+1]]
}
