// Code generated by "stringer -type=InputActions -trimprefix InputAction"; DO NOT EDIT.

package chkb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InputActionNil-0]
	_ = x[InputActionDown-1]
	_ = x[InputActionUp-2]
}

const _InputActions_name = "NilDownUp"

var _InputActions_index = [...]uint8{0, 3, 7, 9}

func (i InputActions) String() string {
	if i < 0 || i >= InputActions(len(_InputActions_index)-1) {
		return "InputActions(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InputActions_name[_InputActions_index[i]:_InputActions_index[i+1]]
}
