// Code generated by "stringer -type=KbActions -trimprefix KbAction"; DO NOT EDIT.

package chkb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KbActionNil - -1]
	_ = x[KbActionMap-0]
	_ = x[KbActionDown-1]
	_ = x[KbActionUp-2]
	_ = x[KbActionTap-3]
	_ = x[KbActionDoubleTap-4]
	_ = x[KbActionHold-5]
	_ = x[KbActionPushLayer-6]
	_ = x[KbActionPopLayer-7]
}

const _KbActions_name = "NilMapDownUpTapDoubleTapHoldPushLayerPopLayer"

var _KbActions_index = [...]uint8{0, 3, 6, 10, 12, 15, 24, 28, 37, 45}

func (i KbActions) String() string {
	i -= -1
	if i < 0 || i >= KbActions(len(_KbActions_index)-1) {
		return "KbActions(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _KbActions_name[_KbActions_index[i]:_KbActions_index[i+1]]
}
